// <auto-generated />
using System;
using ExpenseCompliance.Domain.Claims;
using ExpenseCompliance.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace ExpenseCompliance.Infrastructure.Migrations
{
    [DbContext(typeof(ExpenseComplianceDbContext))]
    partial class ExpenseComplianceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseCompliance.Domain.Claims.ExpenseClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BusinessPurpose")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<ExpenseCategory>("Category")
                        .HasConversion<string>()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasMaxLength(3)
                        .IsFixedLength()
                        .HasColumnType("char(3)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<ClaimStatus>("Status")
                        .HasConversion<string>()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.ToTable("ExpenseClaims", t =>
                        {
                            t.HasCheckConstraint(
                                "CK_ExpenseClaims_Amount_Positive",
                                "[Amount] > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
